
name: 部署文档

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Create .npmrc file
        run: |
          echo "//packages.aliyun.com/638a07cb09a6ccfdd6a1f934/npm/npm-registry/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: 安装依赖
        run: npm ci

      - uses: actions/cache@v4
        with:
          path: dist/.cache
          key: cache-dist

      - name: Exporting
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_SPACE_ID: ${{ secrets.FEISHU_SPACE_ID }}
        uses: longbridge/feishu-pages@main
        # run: npx feishu-pages

      - name: Build Website
        run: |
          cp -r dist/docs/* docs/
          cp dist/docs.json ./

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: npm run docs:build


      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: .vitepress/dist
